DROP TABLE Planet_stats CASCADE CONSTRAINTS;
DROP TABLE Battle_stats CASCADE CONSTRAINTS;
DROP TABLE Battle_log CASCADE CONSTRAINTS;
DROP TABLE Planet_battle_defense CASCADE CONSTRAINTS;
DROP TABLE Planet_battle_army CASCADE CONSTRAINTS;
DROP TABLE Enemy_army CASCADE CONSTRAINTS;

DROP SEQUENCE planet_id_seq;
DROP SEQUENCE num_battle_seq;
DROP SEQUENCE num_line_seq;
